### ISSUE TITLE
doesn't work for me

### ISSUE THREAD

**Issue by pinggit** [paulkass/jira-vim#45]
when I send:

```
:JiraVimBoardOpen TEST
```

I got:

```
Error detected while processing function <SNR>39_JiraVimBoardOpen[3]..check#CheckStorageSession[5]..load_function#LoadS
essionStorage:
line    7:
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api
/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'
),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent'
: 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': '
keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceede
d with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
 failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will retry [1/3] i
n 13.881852947900608s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with
 url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify faile
d (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api
/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'
),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent'
: 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': '
keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceede
d with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
 failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
```

**Comment by paulkass** [comment]
A number of issues might be the cause of this. Have you disabled SSL in your API settings? Perhaps you don't have the SSL packages installed? I found this post on StackOverflow, might be of help: https://stackoverflow.com/questions/34503206/ssl-certificate-verify-failed-error-when-scraping-https-www-thenewboston-co#34503805. 

Let us know if any of this works/any new information that you obtain.

**Comment by pinggit** [comment]
I really have no idea what to do next. by the way I'm running vim in WSL (windows subsystem linux), not sure if that is related though. I don't see an option to disable SSL anywhere...
also btw what is the parameter given to :JiraVimBoardOpen command?

suppose I want to open this ticket:
https://contrail-jws.atlassian.net/browse/CEM-10711

what shall I give to the JiraVimBoardOpen command?

**Comment by pinggit** [comment]
I did a test with curl and get some clues:

```
$ curl -v https://contrail-jws.atlassian.net --user MYACCOUNT:MYTOKEN    
* Rebuilt URL to: https://contrail-jws.atlassian.net/                                              
*   Trying 18.246.31.138...                                                                        
* TCP_NODELAY set                                                                                  
* Connected to contrail-jws.atlassian.net (18.246.31.138) port 443 (#0)                            
* ALPN, offering h2                                                                                
* ALPN, offering http/1.1                                                                          
* successfully set certificate verify locations:                                                   
*   CAfile: /etc/ssl/certs/ca-certificates.crt                                                     
  CApath: /etc/ssl/certs                                                                           
* (304) (OUT), TLS handshake, Client hello (1):                                                    
* (304) (IN), TLS handshake, Server hello (2):                                                     
* (304) (IN), TLS Unknown, Certificate Status (22):                                                
* (304) (IN), TLS handshake, Unknown (8):                                                          
* (304) (IN), TLS Unknown, Certificate Status (22):                                                
* (304) (IN), TLS handshake, Certificate (11):                                                     
* (304) (OUT), TLS alert, Server hello (2):                                                        
* SSL certificate problem: self signed certificate in certificate chain                            
* stopped the pause stream!                                                                        
* Closing connection 0                                                                             
curl: (60) SSL certificate problem: self signed certificate in certificate chain                   
More details here: https://curl.haxx.se/docs/sslcerts.html                                         
                                                                                                   
curl failed to verify the legitimacy of the server and therefore could not                         
establish a secure connection to it. To learn more about this situation and                        
how to fix it, please visit the web page mentioned above.                                          
```

so https://curl.haxx.se/docs/sslcerts.html gives the root cause "self signed certificate in certificate chain" and it gives a long list of workaround.

with curl -k it works now. but how to workaround in your plugin based on this?

**Comment by paulkass** [comment]
Alright, I think I see the error. The error, it seems like, stems from the fact that the cert you have on your jira instance is somehow invalid. What you can do is instead of putting `contrail-jws` as the `g:jiraVimDomainName`, try putting `http://contrail-jws.atlassian.net`. If you look at the code in `python/common/connection.py`, you will see that if you put the name as an actual `http` URL, it will use that as the Atlassian API endpoint. By using `http` instead of `https`, you might be able to avoid the SSL certificate issue.

**Comment by pinggit** [comment]
I see same errors:
and, what parameter I should put after the command? I just copy 'TEST' from your example..

```
Loading board TEST
Error detected while processing function <SNR>39_JiraVimBoardOpen[3]..check#CheckStorageSession[5]..load_function#LoadSessionStorage:
line    7:
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Acce
pt': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_F
AILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will retry [1/3] in 12.506485686745341s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443):
Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1,
```

**Comment by pinggit** [comment]
more stuff keep popping out..

```
line    7:
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Acce
pt': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_F
AILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will retry [1/3] in 12.506485686745341s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443):
Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Acce
pt': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_F
AILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will retry [2/3] in 30.89241885779817s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): M
ax retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Acce
pt': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_F
AILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will retry [3/3] in 55.93941615096378s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): M
ax retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate ve
rify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Acce
pt': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
-- More --
```

**Comment by paulkass** [comment]
Ah, the parameter is the board name. On my test instance, I have a board named TEST, so I used that. You should probably use whatever board name you want to look at.

Also, the error stack still shows that it's using HTTPS. Are you sure you assigned `g:jiraVimDomainName` to `http://contrail-jws.atlassian.net`?

**Comment by pinggit** [comment]
thanks. but I still don't know what is a "board" name.
is it "dashboard"? or "project"? where can I find that name?
normally I just need to access bug reports sth like https://contrail-jws.atlassian.net/browse/CEM-10711. not sure if that indicates a board name...

yes I do have that configured:

```
:let g:jiraVimDomainName
g:jiraVimDomainName    http://contrail-jws.atlassian.net
```

**Comment by pinggit** [comment]
and with `-k` is to bypass the ssl I believe? and here is the log when it works:

```
$ curl -kv https://contrail-jws.atlassian.net --user MYEMAIL:MYTOKEN
* Rebuilt URL to: https://contrail-jws.atlassian.net/
*   Trying 18.246.31.137...
* TCP_NODELAY set
* Connected to contrail-jws.atlassian.net (18.246.31.137) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS change cipher, Client hello (1):
* (304) (OUT), TLS Unknown, Certificate Status (22):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using unknown / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.atlassian.net
*  start date: Dec 23 19:38:55 2019 GMT
*  expire date: Jan 21 19:38:55 2021 GMT
*  issuer: C=US; ST=California; L=Sunnyvale; O=xx Networks; OU=cdd5ca3a4ab2f109a5090147ac37d266; CN=ca.xx.goskope.com; emailAddress=certadmin@netskope.com
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Server auth using Basic with user 'MYEMAIL'
* (304) (OUT), TLS Unknown, Unknown (23):
> GET / HTTP/1.1
> Host: contrail-jws.atlassian.net
> Authorization: Basic cGluZ3NAanVuaXBlci5uZXQ6U3FTVThsVGVyTVNFTmhROXJTcWND
> User-Agent: curl/7.58.0
> Accept: */*
>
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Certificate Status (22):
* (304) (IN), TLS handshake, Newsession Ticket (4):
* (304) (IN), TLS Unknown, Unknown (23):
< HTTP/1.1 302
< Server: AtlassianProxy/1.15.8.1
< Content-Type: text/html;charset=UTF-8
< Strict-Transport-Security: max-age=315360000; includeSubDomains; preload
< Date: Wed, 12 Feb 2020 14:12:51 GMT
< ATL-TraceId: 4e19d7e7fc21174d
< Location: /secure/MyJiraHome.jspa
< X-AREQUESTID: eabc7c13-b186-450e-8c82-75786dd3f51b
< X-XSS-Protection: 1; mode=block
< Timing-Allow-Origin: *
< X-Content-Type-Options: nosniff
< Connection: keep-alive
< Content-Length: 0
<
* Connection #0 to host contrail-jws.atlassian.net left intact

```

**Comment by paulkass** [comment]
A board is basically a way to view the issues and your progress on those issues in a reasonable manner. More documentation here: https://confluence.atlassian.com/jirasoftwarecloud/what-is-a-board-764477964.html. 

In your case, since you want to look at a particular issue, you might have better luck trying to use `:JiraVimIssueOpen CEM-10711` since that goes and directly opens the issue.

**Comment by pinggit** [comment]
got it. thanks. still can't bypass the ssl error anyway...
seems like there is no way to emulate what curl -k would do?

```
 -k, --insecure
        (TLS) By default, every SSL connection curl makes is verified to be secure.  This  option
        allows curl to proceed and operate even for server connections otherwise considered inse‐
        cure.

        The server connection is verified by making sure the server's  certificate  contains  the
        right name and verifies successfully using the cert store.

        See this online resource for further details:
         https://curl.haxx.se/docs/sslcerts.html

        See also --proxy-insecure and --cacert.
```


```
Error detected while processing function <SNR>40_JiraVimIssueOpen[3]..check#CheckStorageSession[5]..load_f
unction#LoadSessionStorage:
line    7:
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with u
rl: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'
params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Ac
cept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Typ
e': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max re
tries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_
FAILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/r
est/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET
]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will
retry [1/3] in 19.81957365164663s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443):
Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_V
ERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with u
rl: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'
params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Ac
cept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Typ
e': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max re
tries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_
FAILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/r
est/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET
]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will
retry [2/3] in 21.078100718012855s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443):
 Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_
VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with u
rl: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'
params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Ac
cept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Typ
e': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max re
tries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_
FAILED] certificate verify failed (_ssl.c:852)'),))] errno:None on GET http://contrail-jws.atlassian.net/r
est/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}\{'response': None, 'request': <PreparedRequest [GET
]>}
WARNING:root:Got recoverable error from GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo, will
retry [3/3] in 19.26091851545899s. Err: HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443):
Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_V
ERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
WARNING:root:HTTPSConnectionPool(host='contrail-jws.atlassian.net', port=443): Max retries exceeded with u
rl: /rest/api/2/serverInfo (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:852)'),)) while doing GET http://contrail-jws.atlassian.net/rest/api/2/serverInfo [{'
params': None, 'headers': {'User-Agent': 'python-requests/2.18.4', 'Accept-Encoding': 'gzip, deflate', 'Ac
cept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Typ
-- More --
```

**Comment by pinggit** [comment]
I'm feeling solution listed in here https://curl.haxx.se/docs/sslcerts.html will help, but I don't see a good steps to follow.

also, does this give a hint to you, is it possible to add one option in vim config to use insecure connection? (verify: false)

https://community.atlassian.com/t5/Jira-Service-Desk-questions/Authorisation-Jira-database-from-Python/qaq-p/941106

**Comment by pinggit** [comment]
posted in jira community, not sure I can get an answer or not..

https://community.atlassian.com/t5/Jira-questions/SSLError-CERTIFICATE-VERIFY-FAILED-from-script/qaq-p/1304154#M409125

a similiar issue were reported and resolved:

https://confluence.atlassian.com/sourcetreekb/resolving-ssl-self-signed-certificate-errors-284368425.html?_ga=2.243049602.1440199052.1582043601-711401452.1555878035#ResolvingSSLSelf-SignedCertificateErrors-SSLcertificatesandMercurial

but I'm not sure how to address it from vim  plugin perspective...

**Comment by jpierson** [comment]
@pinggit , it looks like your traffic is being intercepted by the NetSkope service and tooling which provides a custom certificate instead of the one from the original sites. I've seen this cause a problem in a bunch of development cases and if you haven't found the source of your issue this may be related. See the [related SO article](https://stackoverflow.com/questions/58401781/ssl-fails-with-all-hosts-ssl-certificate-problem-self-signed-certificate-in-c) for more info.
