### ISSUE TITLE
Vim 8.1 - not working - NameError: name 'sessionStorage' is not defined

### ISSUE THREAD

**Issue by maricn** [paulkass/jira-vim#47]
**Describe the bug**
No command from this plugin works.

**To Reproduce**
1. Open vim
2. Run any jira-vim command, such as `:JiraVimSearchAssigned`
4. See error `NameError: name 'sessionStorage' is not defined` - see below

**Screenshots**
![image](https://user-images.githubusercontent.com/3995223/75976642-19af7780-5edb-11ea-867e-0b23de39b7b7.png)

**Desktop (please complete the following information):**
 - OS: MX Linux 19 (Linux work-x1c-mx19 5.5.0-2.1-liquorix-amd64 #1 ZEN SMP PREEMPT liquorix 5.5-3.1~buster (2020-02-06) x86_64 GNU/Linux)
 - Vim: 8.1 (with python3) - see below

**Additional context**
Error:
```
Error detected while processing function <SNR>25_JiraVimSearch[3]..check#CheckStorageSession[5]..load_function#LoadSessionStorage:
line    7:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 6, in __init__
    self.connection = SessionObject.getConnectionFromVars()
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 41, in getConnectionFromVars
    return Connection(domainName, email, token)
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/connection.py", line 17, in __init__
    self.__buildBoardHash()
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/connection.py", line 65, in __buildBoardHash
    bName = re.match(r"\A([\s\w]+)\sboard\Z", v["name"]).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Error detected while processing function <SNR>25_JiraVimSearch:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'sessionStorage' is not defined

```

Vim version:
```
nikola@work-x1c-mx19 Tools/jira-vim (master) » vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 15 2019 16:41:15)
Included patches: 1-875, 878, 884, 948, 1046, 1365-1368, 1382, 1401
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    +tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +textprop
+byte_offset       -hangul_input      +num64             +timers
+channel           +iconv             +packages          +title
+cindent           +insert_expand     +path_extra        +toolbar
+clientserver      +job               +perl              +user_commands
+clipboard         +jumplist          +persistent_undo   +vartabs
+cmdline_compl     +keymap            +postscript        +vertsplit
+cmdline_hist      +lambda            +printer           +virtualedit
+cmdline_info      +langmap           +profile           +visual
+comments          +libcall           -python            +visualextra
+conceal           +linebreak         +python3           +viminfo
+cryptv            +lispindent        +quickfix          +vreplace
+cscope            +listcmds          +reltime           +wildignore
+cursorbind        +localmap          +rightleft         +wildmenu
+cursorshape       +lua               +ruby              +windows
+dialog_con_gui    +menu              +scrollbind        +writebackup
+diff              +mksession         +signs             +X11
+digraphs          +modify_fname      +smartindent       -xfontset
+dnd               +mouse             +startuptime       +xim
-ebcdic            +mouseshape        +statusline        +xpm
+emacs_tags        +mouse_dec         -sun_workshop      +xsmp_interact
+eval              +mouse_gpm         +syntax            +xterm_clipboard
+ex_extra          -mouse_jsbterm     +tag_binary        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-4Pursk/vim-8.1.0875=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.28/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm     
```

**Comment by paulkass** [comment]
Hey @maricn , can you describe if you can the "boards" that you have in your Jira instance?

**Comment by paulkass** [comment]
Might be related to #46 , which already has a feature branch in there.

**Comment by maricn** [comment]
@paulkass We have lots of boards, some Kanban, some Scrum, some other type.
I've tried opening boards by name, and that didn't work. But nothing else doesn't work as well, that's why my i opened the issue with `:JiraVimSearchAssigned` example..

Now i tried these:
* `:JiraVimBoardOpen Authentication`
* `:JiraVimBoardOpen BackBoard`
* `:JiraVimBoardOpen Design Board`

and I always get the same error.

P.S. I tried both the boards that are under my profile and some that are under shared project. I am also admin of the jira instance, so privileges shouldn't be an issue.

**Comment by paulkass** [comment]
That seems exactly like the other issue that I tagged, the person there
also had board names that don't end with `board`. Let me try to get his
changes in and see what happens.

Thanks,
Paul Kassianik

**Comment by paulkass** [comment]
Try now, I merged a fix that should fix this PR. Let me know if you still see the issue!

**Comment by maricn** [comment]
Thanks for your response and fix!

Now:
* `Authentication` board is working (no board in the name)
* `BackBoard` board is working (with board in the name)
* `Design Board` board is not working (has spaces in the name)

The last one fails with `AttributeError: 'NoneType' object has no attribute 'id'`. I tried escaping the space with backslash, and quoting it in single and double quotation marks, no change (the same error happens).


```
Loading board "Design Board"
Error detected while processing function <SNR>21_JiraVimBoardOpen:
line    5:
  File "<string>", line 1
    sys.argv = [""Design Board""]
                       ^
SyntaxError: invalid syntax
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/boards/open.py", line 17, in JiraVimBoardOpen
    board = sessionStorage.getBoard(buf.number, boardName=boardName)
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 129, in getBoard
    self.assignBoard(board, vim.buffers[buf])
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 60, in assignBoard
    self.__bufferHash[board.id] = buff
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by paulkass** [comment]
Try now, and call `JiraVimBoardOpen Design Board` now instead of putting it in quotes.

**Comment by maricn** [comment]
I updated the plugin, but still have the problem:

```
Loading board Design Board
Error detected while processing function <SNR>21_JiraVimBoardOpen:
line    6:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/boards/open.py", line 17, in JiraVimBoardOpen
    board = sessionStorage.getBoard(buf.number, boardName=boardName)
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 129, in getBoard
    self.assignBoard(board, vim.buffers[buf])
  File "/home/nikola/.dotfiles-go-vim/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 60, in assignBoard
    self.__bufferHash[board.id] = buff
AttributeError: 'NoneType' object has no attribute 'id'
Press ENTER or type command to continue
```

**Comment by paulkass** [comment]
curious, what would happen if you did `JiraVimBoardOpen Design`?

**Comment by maricn** [comment]
> curious, what would happen if you did `JiraVimBoardOpen Design`?

:boom: there's our design board :D

**Comment by maricn** [comment]
but it's strange... when I do:
* `:JiraVimBoardOpen Design` it works (for "Design Board" Kanban board)
* `:JiraVimBoardOpen design` it doesn't work (lower case)
* `:JiraVimBoardOpen Data` (for "Data Loop" Kanban board) it also doesn't work

**Comment by paulkass** [comment]
Yeah, the board name is case sensitive. The reason `JiraVimBoardOpen
Design` works is because the board name ends in `Board`. So for Data Loop,
you would say `JiraVimBoardOpen Data Loop`.

Thanks,
Paul Kassianik

**Comment by maricn** [comment]
> Yeah, the board name is case sensitive. The reason `JiraVimBoardOpen Design` works is because the board name ends in `Board`. So for Data Loop, you would say `JiraVimBoardOpen Data Loop`. Thanks, Paul Kassianik

OK about case sensitivity.

But `:JiraVimBoardOpen Data Loop` fails with the same error `AttributeError: 'NoneType' object has no attribute 'id'`

P.S. Don't get me wrong, sorry for the nitpicks, I'm just trying to be helpful :)

**Comment by paulkass** [comment]
Hmm @maricn , I created a board on my test jira instance with a space in between, and it opens fine. It's also a kanban board. Can we take this to gitter to debug a bit more?

Just in case, it's recommended to restart vim every time you update JiraVim.

**Comment by maricn** [comment]
OK, figured it out @paulkass - it was "Data loop" not "Data Loop"..

Thanks for your assistance and good luck with the plugin!
