### ISSUE TITLE
Can't open a board if its name contains spaces (or a colon)

### ISSUE THREAD

**Issue by khiebiggs** [paulkass/jira-vim#57]
**Describe the bug**
I can't seem to open a jira board if the board name contains spaces (or perhaps a colon?).
My company formats board names like the following: `Team Board: Team Name`
Trying to run `:JiraVimBoardOpen Team Board: Team Name` results in the following error (modified for privacy):

```
Loading board Team Board: Team Name    
Error detected while processing function <SNR>61_JiraVimBoardOpen[6]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 4 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/name/.vim/plugged/jira-vim/plugin/../python/boards/open.py", line 17, in JiraVimBoardOpen
    board = sessionStorage.getBoard(buf.number, boardName=boardName)
  File "/home/name/.vim/plugged/jira-vim/plugin/../python/common/sessionObject.py", line 128, in getBoard
    board = self.__boardsHash.get(buf, create_new_object(boardName))
  File "/home/name/.vim/plugged/jira-vim/plugin/../python/common/connection.py", line 119, in getBoard
    return ScrumBoard(boardId, board_name, self)
  File "/home/name/.vim/plugged/jira-vim/plugin/../python/common/scrumBoard.py", line 20, in __init__
    startDate=sprintObj["startDate"],
KeyError: 'startDate'
```

**To Reproduce**

Try to open a board with spaces (or a colon?)

**Expected behavior**
To see the board

Is there any way to open a board using the board id instead? Thanks for the great plugin!

**Comment by paulkass** [comment]
Hey @khiebiggs , have you tried doing `:JiraVimBoardOPen 'Team Board: Team Name'`? I have a feeling it might be trying to find the board `Team` but that doesn't exist, so it's throwing this error ...
